/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OptionalAuthRouteImport } from './routes/_optionalAuth'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as MustAuthRouteRouteImport } from './routes/_mustAuth/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MustAuthIndexRouteImport } from './routes/_mustAuth/index'
import { Route as SettingsNotificationRouteImport } from './routes/settings/notification'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as OptionalAuthUsernameRouteImport } from './routes/_optionalAuth.$username'
import { Route as MustAuthSearchRouteImport } from './routes/_mustAuth/search'
import { Route as MustAuthExploreRouteImport } from './routes/_mustAuth/explore'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OptionalAuthRoute = OptionalAuthRouteImport.update({
  id: '/_optionalAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MustAuthRouteRoute = MustAuthRouteRouteImport.update({
  id: '/_mustAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const MustAuthIndexRoute = MustAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const SettingsNotificationRoute = SettingsNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionalAuthUsernameRoute = OptionalAuthUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => OptionalAuthRoute,
} as any)
const MustAuthSearchRoute = MustAuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const MustAuthExploreRoute = MustAuthExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/explore': typeof MustAuthExploreRoute
  '/search': typeof MustAuthSearchRoute
  '/$username': typeof OptionalAuthUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/': typeof MustAuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/explore': typeof MustAuthExploreRoute
  '/search': typeof MustAuthSearchRoute
  '/$username': typeof OptionalAuthUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/': typeof MustAuthIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_mustAuth': typeof MustAuthRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_optionalAuth': typeof OptionalAuthRouteWithChildren
  '/_mustAuth/explore': typeof MustAuthExploreRoute
  '/_mustAuth/search': typeof MustAuthSearchRoute
  '/_optionalAuth/$username': typeof OptionalAuthUsernameRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/_mustAuth/': typeof MustAuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/explore'
    | '/search'
    | '/$username'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/explore'
    | '/search'
    | '/$username'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_mustAuth'
    | '/settings'
    | '/_optionalAuth'
    | '/_mustAuth/explore'
    | '/_mustAuth/search'
    | '/_optionalAuth/$username'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/_mustAuth/'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MustAuthRouteRoute: typeof MustAuthRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  OptionalAuthRoute: typeof OptionalAuthRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_optionalAuth': {
      id: '/_optionalAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OptionalAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mustAuth': {
      id: '/_mustAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MustAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_mustAuth/': {
      id: '/_mustAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MustAuthIndexRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/settings/notification': {
      id: '/settings/notification'
      path: '/notification'
      fullPath: '/settings/notification'
      preLoaderRoute: typeof SettingsNotificationRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_optionalAuth/$username': {
      id: '/_optionalAuth/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof OptionalAuthUsernameRouteImport
      parentRoute: typeof OptionalAuthRoute
    }
    '/_mustAuth/search': {
      id: '/_mustAuth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MustAuthSearchRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/_mustAuth/explore': {
      id: '/_mustAuth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MustAuthExploreRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MustAuthRouteRouteChildren {
  MustAuthExploreRoute: typeof MustAuthExploreRoute
  MustAuthSearchRoute: typeof MustAuthSearchRoute
  MustAuthIndexRoute: typeof MustAuthIndexRoute
}

const MustAuthRouteRouteChildren: MustAuthRouteRouteChildren = {
  MustAuthExploreRoute: MustAuthExploreRoute,
  MustAuthSearchRoute: MustAuthSearchRoute,
  MustAuthIndexRoute: MustAuthIndexRoute,
}

const MustAuthRouteRouteWithChildren = MustAuthRouteRoute._addFileChildren(
  MustAuthRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsNotificationRoute: typeof SettingsNotificationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsNotificationRoute: SettingsNotificationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface OptionalAuthRouteChildren {
  OptionalAuthUsernameRoute: typeof OptionalAuthUsernameRoute
}

const OptionalAuthRouteChildren: OptionalAuthRouteChildren = {
  OptionalAuthUsernameRoute: OptionalAuthUsernameRoute,
}

const OptionalAuthRouteWithChildren = OptionalAuthRoute._addFileChildren(
  OptionalAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MustAuthRouteRoute: MustAuthRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  OptionalAuthRoute: OptionalAuthRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
