/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as MustAuthRouteRouteImport } from './routes/_mustAuth/route'
import { Route as UsernameRouteRouteImport } from './routes/$username/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MustAuthIndexRouteImport } from './routes/_mustAuth/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as SettingsNotificationRouteImport } from './routes/settings/notification'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as MustAuthSearchRouteImport } from './routes/_mustAuth/search'
import { Route as MustAuthExploreRouteImport } from './routes/_mustAuth/explore'
import { Route as UsernameTaggedRouteImport } from './routes/$username/tagged'
import { Route as UsernameSavedRouteImport } from './routes/$username/saved'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MustAuthRouteRoute = MustAuthRouteRouteImport.update({
  id: '/_mustAuth',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRouteRoute = UsernameRouteRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const MustAuthIndexRoute = MustAuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameRouteRoute,
} as any)
const SettingsNotificationRoute = SettingsNotificationRouteImport.update({
  id: '/notification',
  path: '/notification',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MustAuthSearchRoute = MustAuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const MustAuthExploreRoute = MustAuthExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => MustAuthRouteRoute,
} as any)
const UsernameTaggedRoute = UsernameTaggedRouteImport.update({
  id: '/tagged',
  path: '/tagged',
  getParentRoute: () => UsernameRouteRoute,
} as any)
const UsernameSavedRoute = UsernameSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => UsernameRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$username': typeof UsernameRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$username/saved': typeof UsernameSavedRoute
  '/$username/tagged': typeof UsernameTaggedRoute
  '/explore': typeof MustAuthExploreRoute
  '/search': typeof MustAuthSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/$username/': typeof UsernameIndexRoute
  '/': typeof MustAuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/$username/saved': typeof UsernameSavedRoute
  '/$username/tagged': typeof UsernameTaggedRoute
  '/explore': typeof MustAuthExploreRoute
  '/search': typeof MustAuthSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/$username': typeof UsernameIndexRoute
  '/': typeof MustAuthIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$username': typeof UsernameRouteRouteWithChildren
  '/_mustAuth': typeof MustAuthRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/$username/saved': typeof UsernameSavedRoute
  '/$username/tagged': typeof UsernameTaggedRoute
  '/_mustAuth/explore': typeof MustAuthExploreRoute
  '/_mustAuth/search': typeof MustAuthSearchRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/$username/': typeof UsernameIndexRoute
  '/_mustAuth/': typeof MustAuthIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$username'
    | '/settings'
    | '/$username/saved'
    | '/$username/tagged'
    | '/explore'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/$username/'
    | '/'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$username/saved'
    | '/$username/tagged'
    | '/explore'
    | '/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/$username'
    | '/'
    | '/settings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/$username'
    | '/_mustAuth'
    | '/settings'
    | '/$username/saved'
    | '/$username/tagged'
    | '/_mustAuth/explore'
    | '/_mustAuth/search'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/settings/notification'
    | '/$username/'
    | '/_mustAuth/'
    | '/settings/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UsernameRouteRoute: typeof UsernameRouteRouteWithChildren
  MustAuthRouteRoute: typeof MustAuthRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mustAuth': {
      id: '/_mustAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MustAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/_mustAuth/': {
      id: '/_mustAuth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MustAuthIndexRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/$username/': {
      id: '/$username/'
      path: '/'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof UsernameRouteRoute
    }
    '/settings/notification': {
      id: '/settings/notification'
      path: '/notification'
      fullPath: '/settings/notification'
      preLoaderRoute: typeof SettingsNotificationRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mustAuth/search': {
      id: '/_mustAuth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MustAuthSearchRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/_mustAuth/explore': {
      id: '/_mustAuth/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof MustAuthExploreRouteImport
      parentRoute: typeof MustAuthRouteRoute
    }
    '/$username/tagged': {
      id: '/$username/tagged'
      path: '/tagged'
      fullPath: '/$username/tagged'
      preLoaderRoute: typeof UsernameTaggedRouteImport
      parentRoute: typeof UsernameRouteRoute
    }
    '/$username/saved': {
      id: '/$username/saved'
      path: '/saved'
      fullPath: '/$username/saved'
      preLoaderRoute: typeof UsernameSavedRouteImport
      parentRoute: typeof UsernameRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UsernameRouteRouteChildren {
  UsernameSavedRoute: typeof UsernameSavedRoute
  UsernameTaggedRoute: typeof UsernameTaggedRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
}

const UsernameRouteRouteChildren: UsernameRouteRouteChildren = {
  UsernameSavedRoute: UsernameSavedRoute,
  UsernameTaggedRoute: UsernameTaggedRoute,
  UsernameIndexRoute: UsernameIndexRoute,
}

const UsernameRouteRouteWithChildren = UsernameRouteRoute._addFileChildren(
  UsernameRouteRouteChildren,
)

interface MustAuthRouteRouteChildren {
  MustAuthExploreRoute: typeof MustAuthExploreRoute
  MustAuthSearchRoute: typeof MustAuthSearchRoute
  MustAuthIndexRoute: typeof MustAuthIndexRoute
}

const MustAuthRouteRouteChildren: MustAuthRouteRouteChildren = {
  MustAuthExploreRoute: MustAuthExploreRoute,
  MustAuthSearchRoute: MustAuthSearchRoute,
  MustAuthIndexRoute: MustAuthIndexRoute,
}

const MustAuthRouteRouteWithChildren = MustAuthRouteRoute._addFileChildren(
  MustAuthRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsNotificationRoute: typeof SettingsNotificationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsNotificationRoute: SettingsNotificationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UsernameRouteRoute: UsernameRouteRouteWithChildren,
  MustAuthRouteRoute: MustAuthRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
